#!/bin/bash
# vim: autoindent tabstop=4 shiftwidth=4 expandtab softtabstop=4 filetype=bash
# -*- mode: sh; indent-tabs-mode: nil; sh-basic-offset: 4 -*-

set -x

seconds=600
opts=$(getopt -q -o "" --longoptions "seconds:" -n "getopt.sh" -- "$@");
eval set -- "$opts";
while true; do
    case "$1" in
        --seconds)
            shift
            seconds=$1
            shift
            ;;
        --)
            shift
            break
            ;;
        *)
            shift
            ;;
    esac
done


date +%s.%N >sleep-start.txt
sleep $seconds
date +%s.%N >sleep-stop.txt
